theme: jekyll-theme-minimal
title: "Use and outcomes of beta blockers among Medicare beneficiaries hospitalized for heart failure with reduced ejection fraction"
author: "Matthew Shane Loop, PhD FAHA"
